-- CreateTable
CREATE TABLE `Objective` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `taskId` INTEGER NOT NULL,
  `description` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'ONGOING',
  `createdDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedDate` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`),
  CONSTRAINT `Objective_taskId_fkey` FOREIGN KEY (`taskId`) REFERENCES `Task` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);
